### ISSUE TITLE
Connect OPD UART to UART0

### ISSUE THREAD

**Issue by cesarordaz** [oresat/oresat-dxwifi-hardware#16]
UART lines from the TS5A21366 OPD UART switch should be connected to UART0 which goes to the debug connector.
This is so that the C3 can communicate directly with the Octavo.

i.e. the nets UART0_Tx(C3-Rx) and UART0_Rx(C3-Tx) should be changed to UART0_Tx and UART0_Rx.

**Comment by NickLekas** [comment]
Done
